name: Run Python Script

on:
  schedule:
    - cron: '30 13 * * *'  # Run at 1:30 PM every day
  workflow_dispatch:  # Trigger for manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      GIST_URL: ${{ secrets.ACCOUNTFILESOURCE }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
      env:
        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 120

    - name: Download accounts.json
      run: |
        curl -L $GIST_URL -o accounts.json

    - name: Run Python Script
      run: |
        python main.py \
          -g CA
